# Generated by Django 5.2.12 on 2026-03-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklistapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlackListWords',
            new_name='BlacklistWord',
        ),
    ]
